name: 'Python CI'
description: 'Checks code for compilation error'

runs:
  using: 'composite'

  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  

    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash

    - name: Run the main python file
      run: main.py
      shell: bash