name: 'Python CI'

on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  

      - name: Install Dependencies
        run: pip install -r ${{ github.workspace }}/requirements.txt
        shell: bash

      - name: Run the main python file
        run: python main.py
        shell: bash