name: Docker Build Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t my-docker-image .
        continue-on-error: true

      - name: Check if Docker image built successfully
        run: docker inspect my-docker-image

      - name: Verify Docker build success
        run: exit $(docker inspect my-docker-image > /dev/null)
