site_name: Cansat Ground Station
site_author: Cansat
docs_dir: Docs

theme:
  name: material
  feature:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotations
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: pink
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: pink
      accent: lime
  language: en


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md

copyright: |
  &copy; 2024 <a href="https://github.com/Gagan-Space/Cansat-Ground-Station"  target="_blank" rel="noopener">Gagan-Space</a>